spring:
  datasource:
    url: jdbc:mysql://db:3306/weather_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    by.weather: debug

properties:
  location: minsk
  period: 60000 #in milliseconds
  rapid-key: ${secret.rapid-key}